name: research-crew
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.10
  - pytorch=2.2.1
  - pytorch-cuda=11.8
  - faiss-gpu
  - pip
  - pip:
      - arxiv
      - transformers
      - pypdf
      - crewai==0.16.3
      - tiktoken==0.6.0
      - langchain-community==0.0.20
      - langchain-openai==0.0.8